#2478 SLI evaluation breakdown as barista table (#3023)
keptn/keptn pull request #3053
Opened 2021-02-02 17:01 UTC by johannes-b

2021-02-17 15:10 UTC, Kirdock commented
Also fixes #2475 (the part that is possible)
![image](https://user-images.githubusercontent.com/11599148/108223809-7b8fde00-713a-11eb-8e3d-9a1c8d08f76c.png)

2021-02-18 07:43 UTC, bacherfl requested changes

2021-02-18 07:43 UTC, bacherfl commented on cli/internal/cespec/data.go
> +			PassTargets: []*keptnv2.SLITarget{&keptnv2.SLITarget{
please also add an example for the `WarningTargets` property

2021-02-18 10:54 UTC, johannes-b commented
A minor change: Can you please align the column "Result" to the right. (to have it the same way like "Value", "pass Criteria", "warning Criteria", and "Score")  

![image](https://user-images.githubusercontent.com/729071/108346462-af710f00-71df-11eb-8a24-458c67d28982.png)

2021-02-18 11:02 UTC, johannes-b commented
- [ ] The Score column needs to be fixed. Please see my example below, where I have two metrics: response_time (weight = 1), error_rate (weight=2), response_time resulted in a warning (this means that we get half of the points here). In the end, I would like to see: 
- response_time: Score: 16.5
- error_rate Score: 66

In total, this has to sum up to the 83.

Can you please get this resolved? Other than that, the table is a great feature!

![image](https://user-images.githubusercontent.com/729071/108347448-cbc17b80-71e0-11eb-8977-8c8218503656.png)

2021-02-19 09:45 UTC, ermin-muratovic submitted a review, later dismissed
lgtm

2021-02-19 10:37 UTC, ermin-muratovic approved these changes
lgtm

2021-02-19 12:39 UTC, merged