Smart Helm values merger
keptn/keptn pull request #3318
Opened 2021-02-22 07:44 UTC by agrimmer

Signed-off-by: agrimmer <andreas.grimmer@dynatrace.com>

2021-03-02 16:12 UTC, christian-kreuzberger-dtx commented
I think this PR shows how the merger should work.

Now that we have this feature, is there a chance we can get rid of the [replica_count_manipulator.go](https://github.com/keptn/keptn/blob/master/helm-service/pkg/configurationchanger/replica_count_manipulator.go)?

2021-04-01 12:50 UTC, jsoref requested changes
Please add the other words the bot suggested into `expect.txt`, if you're on Linux, it has a command you can run to do it for you.

2021-04-01 12:50 UTC, jsoref commented on cli/internal/textutils.go
> +	return innerNode{childs: make(map[string]node)}
Generally you want `children`

2021-04-06 05:57 UTC, warber commented
closes #3341

2021-04-06 06:35 UTC, bacherfl commented on cli/internal/textutils.go
> +	childs     map[string]node
can we rename this to `children`?

2021-04-06 06:42 UTC, bacherfl approved these changes

2021-04-06 06:59 UTC, merged