updated to latest structs
keptn/keptn pull request #3322
Opened 2021-02-22 10:08 UTC by warber

Signed-off-by: warber <bernd.warmuth@dynatrace.com>

2021-02-22 11:19 UTC, christian-kreuzberger-dtx requested changes
Please change the PR title to something that's more meaningful and add a description to the PR, indicating why this change is necessary.

2021-02-24 06:58 UTC, bacherfl approved these changes

2021-02-24 12:55 UTC, johannes-b approved these changes
lgtm

2021-02-24 13:02 UTC, christian-kreuzberger-dtx approved these changes
LGTM

2021-02-24 13:08 UTC, merged