#4491 fix refreshing on polling, #4438 wrong selection stage
keptn/keptn pull request #4582
Opened 2021-07-05 14:59 UTC by Kirdock

Fixes #4491 
Fixes #4438 

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

2021-07-06 11:03 UTC, laneli requested changes

2021-07-06 11:03 UTC, laneli commented on bridge/client/app/_views/ktb-service-view/ktb-service-view.component.ts
> +        const paramDeployment = service.deployments.find(deployment => deployment.shkeptncontext === params.shkeptncontext);
Just a nitpick ... as filter returns an array consider it renaming to changedDeployments

2021-07-06 11:56 UTC, Kirdock commented on bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts
>      this.route.params.pipe(
It is available and needed to set the project-parameter before the input-parameters are set

2021-07-06 11:58 UTC, Kirdock commented on bridge/client/app/_components/ktb-service-details/ktb-service-details.component.ts
>              this._changeDetectorRef.markForCheck();
`OnPush` is set, so I would leave it as it is

2021-07-08 07:41 UTC, laneli submitted a review, later dismissed

2021-07-09 07:01 UTC, laneli approved these changes
Looks good

2021-07-09 07:02 UTC, merged