#4615 Automatic expiration of Uniform integrations
keptn/keptn pull request #4675
Opened 2021-07-19 07:29 UTC by bacherfl

Closes #4615

2021-07-26 13:01 UTC, warber submitted a review, later dismissed

2021-07-26 13:36 UTC, warber approved these changes

2021-07-27 06:29 UTC, warber requested changes

2021-07-27 06:29 UTC, warber commented on shipyard-controller/main.go
> +		log.WithError(err).Error("could not setup TTL index for log repo entries")
wrong error message

2021-07-27 06:46 UTC, warber requested changes
looks good, however, changing the `TTL` value results in an `IndexOptionsConflict` error, hence the index will not be changed.

2021-07-27 14:20 UTC, warber approved these changes

2021-07-27 14:24 UTC, thisthat approved these changes

2021-07-27 14:29 UTC, merged