feat(bridge): Show dialog when settings / create project is changed (#4677)
keptn/keptn pull request #4925
Opened 2021-08-12 09:47 UTC by laneli

Signed-off-by: Elisabeth Lang <elisabeth.lang@dynatrace.com>

## This PR
When the user types in something in the create project/project settings form he will get a notification that there are unsaved changes:

![image](https://user-images.githubusercontent.com/2674029/129176305-cef4edd4-1c06-4d69-a2a5-8cfb153f9d90.png)

![image](https://user-images.githubusercontent.com/2674029/129176249-3c5cd6b3-3565-4bee-ad96-f7ef38a7b24f.png)

2021-08-13 08:33 UTC, laneli commented
https://github.com/keptn/keptn/issues/4677#issuecomment-898283678

2021-08-16 09:03 UTC, Kirdock requested changes

2021-08-16 10:56 UTC, laneli commented on bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.ts
> +    if (gitData.gitFormValid !== undefined && gitData.gitFormValid) {
Done :)

2021-08-16 11:00 UTC, laneli commented on bridge/client/app/_views/ktb-settings-view/ktb-settings-view.component.spec.ts
> +  it('should not show a notification when not all git data fields are set', () => {
Done :)

2021-08-16 11:15 UTC, Kirdock submitted a review, later dismissed

2021-08-16 12:50 UTC, Kirdock approved these changes

2021-08-16 12:52 UTC, merged