feat: Introduced WebHook Service (#4736)
keptn/keptn pull request #4938
Opened 2021-08-16 12:03 UTC by bacherfl

Closes #4736 
Closes #4742
Closes #4743

2021-09-02 12:23 UTC, johannes-b commented
I'm playing around with the webhook-service, and it already looks really good.

I just encountered some changes requests: 

### Webhook.conf in ./webhook/

![image](https://user-images.githubusercontent.com/729071/131842090-9dbf527d-49d4-4872-96ce-a1f86e877c83.png)The 
- Right now, the `webhook.conf` is stored directly in the folder of the service. 
- [ ] However, it should be stored in the `webhook` folder. 

### Adoption in `finished` event 

* Right now, the webhook-service returns a `finished` event as follows:
```
{
  "data": {
    "labels": null,
    "project": "sockshop",
    "result": "pass",
    "service": "carts",
    "sh.keptn.event.test.triggered": {
      "responses": [
        "ok"
      ]
    },
    "stage": "dev",
    "status": "succeeded"
  },
  "id": "a3248326-892b-43d0-bda7-0e338c108de0",
  "source": "webhook-service",
  "specversion": "1.0",
  "time": "2021-09-02T12:07:20.593Z",
  "type": "sh.keptn.event.test.finished",
  "shkeptncontext": "49206abf-a201-40d5-945e-4d21d5a76500",
  "triggeredid": "8c8f4598-5cb0-4f11-bf94-21acdc5c6ece"
}
```

- [ ] Change the `data` payload to contain just `test` and not the full event type `sh.keptn.event.test.triggered`

2021-09-06 07:13 UTC, johannes-b commented
## Error log when no webhook.conf available

- [ ] When the webhook-service has a subscription on, e.g., `sh.keptn.event.test.triggered` for all stages (and all services), but not `webhook.conf` file is available, I would like to get an error log telling me about the missing `webhook.conf`.

![image](https://user-images.githubusercontent.com/729071/132175414-fdb65834-4988-40dd-81c2-d23c8c4fd1ed.png)

2021-09-08 10:10 UTC, Kirdock requested changes

2021-09-08 10:10 UTC, Kirdock commented on webhook-service/deploy/service.yaml
> +            - name: PUBSUB_TOPIC
Initially, the webhook service should not be subscribed to any event.

2021-09-15 06:05 UTC, warber submitted a review, later dismissed

2021-09-16 10:53 UTC, johannes-b commented
I encountered a problem with the webhook-service as explained in this image: 

![image](https://user-images.githubusercontent.com/729071/133599795-c3114979-86fd-4ca1-88da-ccdd38e253b6.png)

2021-09-16 13:58 UTC, warber approved these changes

2021-09-16 14:24 UTC, merged