feat: Switch mongoDB image to bitnami mongoDB chart (#4801)
keptn/keptn pull request #5434
Opened 2021-09-29 07:07 UTC by mowies

## This PR

- switches our current CentOS base mongo 3.6 image out for the bitnami maintained mongodb helm chart which uses mongo 4.4

### Related Issues

Fixes #4801

### Notes

### Follow-up Tasks

### How to test

2021-11-04 15:11 UTC, thisthat requested changes
I tested this PR. Everything was correctly restored but the webhook subscriptions

2021-11-04 16:35 UTC, thisthat commented
The error that I get is due to the fact that the uniform integration is built again after the Keptn update and the `keptnUniform` collection contains the default values for the subscriptions of the services. Adding `--drop` to the restore command solves the issue

2021-11-05 07:34 UTC, bacherfl approved these changes

2021-11-08 07:49 UTC, thisthat submitted a review, later dismissed
LGTM

2021-11-08 09:32 UTC, bacherfl approved these changes

2021-11-08 09:40 UTC, merged