fix(webhook-service): Avoid .finished.finished events (#5954)
keptn/keptn pull request #6000
Opened 2021-11-12 10:05 UTC by bacherfl

Closes #5954 

This fixes a problem that caused the webhook service to respond with <task>.finished.finished events when the webhook execution failed

2021-11-12 10:39 UTC, laneli requested changes
The behaviour should work not only for finished events, but also for started events. Atm there are also e.g. `sh.keptn.event.deployment.started.finished` events in the payload

2021-11-12 11:12 UTC, RealAnna approved these changes
LGTM

2021-11-12 11:29 UTC, bacherfl commented
> The behaviour should work not only for finished events, but also for started events. Atm there are also e.g. `sh.keptn.event.deployment.started.finished` events in the payload

The fix addressed those events as well, i.e. everything that is not a <task>.triggered event will not generate any outgoiing events. I have added an additional unit test though

2021-11-12 11:34 UTC, laneli approved these changes

2021-11-15 08:44 UTC, RealAnna approved these changes

2021-11-15 08:45 UTC, merged