feat(cli): created user warning about changed database model when upg…
keptn/keptn pull request #6071
Opened 2021-11-22 08:53 UTC by odubajDT

…rading to keptn 0.11.*

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- creates user warning about changed database model when upgrading to keptn 0.11.*

### Related Issues

Fixes #6070

2021-11-22 09:12 UTC, warber requested changes

2021-11-22 09:12 UTC, warber commented on cli/cmd/upgrade.go
> +
pls use `UserInput` in userinput.go` for this

2021-11-22 09:15 UTC, mowies requested changes
Some small adjustments to the user messages :)

2021-11-22 09:15 UTC, mowies commented on cli/cmd/upgrade.go
> +		fmt.Printf("Please be aware. While upgrading keptn from version %s to version %s there is a possibility of data loss due to moving to new database model.\n", installedKeptnVersion, getAppVersion(ke
```suggestion
		fmt.Printf("CAUTION: While upgrading Keptn from version %s to version %s there is a possibility of data loss due to moving to a new database model.\n", installedKeptnVersion, getAppVersion(keptnUpgradeChart))
```

2021-11-22 09:15 UTC, mowies commented on cli/cmd/upgrade.go
> +		fmt.Printf("Please backup your data before proceeding to the next step. Information about backing up and restoring the data are described here: https://keptn.sh/docs/0.11.x/operate/backup_and_resto
```suggestion
		fmt.Printf("Please backup your data before proceeding to the next step. Information about backing up and restoring the data is described here: https://keptn.sh/docs/0.11.x/operate/backup_and_restore/\n")
```

2021-11-22 09:15 UTC, mowies commented on cli/cmd/upgrade.go
> +		fmt.Printf("Did you created the back-up for the database or do you want to proceed without it? (y/n)\n")
```suggestion
		fmt.Printf("Did you create a backup of the database or do you want to proceed without it? (y/n)\n")
```

2021-11-22 11:50 UTC, warber approved these changes

2021-11-23 08:11 UTC, odubajDT commented
@mowies regarding this PR, when will this page be prepared? https://keptn.sh/docs/0.11.x/operate/backup_and_restore Can we maybe merge this PR also before it is prepared?

Thank you :)

2021-11-23 08:13 UTC, mowies commented
@odubajDT The page update is already done and merged into our docs. So go ahead and merge this PR anytime :)

2021-11-23 08:14 UTC, mowies approved these changes

2021-11-23 08:23 UTC, merged