feat(bridge): Use textarea for webhook url config and adapt styles (#5706)
keptn/keptn pull request #6350
Opened 2021-12-14 12:01 UTC by laneli

* Subscription and webhook forms are now a bit cleaner and more aligned
* Webhook URL is a textarea with standard row size 1 and can be expanded
* The buttons for payload and secret variables are now in the header of both textareas because it would otherwise overlap the content and the expand handle

![image](https://user-images.githubusercontent.com/2674029/145994524-d0dcb956-c942-4238-9008-aeba3adb2eff.png)

2021-12-15 08:15 UTC, Kirdock requested changes
Could you add some padding here for the "Show example payload"-button?
![image](https://user-images.githubusercontent.com/11599148/146147770-c610f9e9-ca6e-4fee-89a4-53a39b1c180a.png)

Should we show the event- and secret picker for the custom headers above the input field like the textareas (to align it with the style of the others)?
![image](https://user-images.githubusercontent.com/11599148/146148254-d1c3e1d8-4389-4027-8a93-7cd25dd96ef5.png)

2021-12-15 13:07 UTC, laneli commented
Adaptions:

![image](https://user-images.githubusercontent.com/2674029/146191807-49d2a2e3-ad50-4cad-bd09-0e0f66b32ec7.png)

![image](https://user-images.githubusercontent.com/2674029/146191888-fdd6c551-42f2-464b-904d-76baf0576109.png)

2021-12-15 14:03 UTC, Kirdock requested changes
One additional minor change:
Could you add a min-height to the textareas? The scrollbar should not show up if the height is set to minimum.
![image](https://user-images.githubusercontent.com/11599148/146200226-592df583-8ffe-4ea4-9107-769bb1f1935a.png)

2021-12-16 07:47 UTC, Kirdock approved these changes

2021-12-16 07:55 UTC, merged