docs: Add structure for developer documentation
keptn/keptn pull request #6671
Opened 2022-01-25 07:40 UTC by thisthat

Signed-off-by: Giovanni Liva <giovanni.liva@dynatrace.com>

This PR adds a structure to our developer documentation

2022-01-25 07:42 UTC, bacherfl commented on docs/core.md
> +This file contains helful resources to start developing with Keptn core services.
helful -> helpful

2022-01-25 09:42 UTC, thisthat commented on docs/README.md
>      * [dynatrace-sli-service](https://github.com/keptn-contrib/dynatrace-sli-service)
I would remove this list and maintain only the pointer to the two orgs. I think it is not maintainable as a list 😓

2022-01-25 09:46 UTC, thisthat commented on docs/README.md
>  ![Branch Workflow](assets/git_branch_workflow.png "Git Branch Workflow")
I agree. I'll add on the top a link towards that file

2022-01-25 09:59 UTC, mowies commented on docs/README.md
> +We reccomend to read our [CONTRIBUTING](../CONTRIBUTING.md) guidelines before reading this document.
```suggestion
We recommend to read our [CONTRIBUTING](../CONTRIBUTING.md) guidelines before reading this document.
```

2022-01-25 10:09 UTC, mowies approved these changes

2022-01-25 11:00 UTC, oleg-nenashev requested changes
I would suggest adding explicit dev prefix or directory to the developer documentation. Later we could move user documentation to the repository too once we have Documentation-as-code in place.

I suggest moving all developer docs to `docs/developer` right away

2022-01-25 12:08 UTC, thisthat commented
I agree with you @oleg-nenashev. I moved the doc into a `/docs/developer` subfolder :)

2022-01-26 08:44 UTC, oleg-nenashev approved these changes
Looks good, thank you for the patch!

FWIW GitHub Web UI now supports table of contents out of the box these days. The current approach is still better for visualization though

2022-01-26 08:49 UTC, merged