fix(bridge): Truncate evaluation score
keptn/keptn pull request #6993
Opened 2022-02-25 08:25 UTC by ermin-muratovic

## This PR
- is truncating the evaluation score correctly

### Related Issues
Fixes #6890 

![image](https://user-images.githubusercontent.com/6098219/155475205-3bbdcac3-9635-4bab-82dd-bbbb5cba04b0.png)

2022-02-25 09:11 UTC, laneli requested changes
Can you please add Unit Tests for any other case that is not 1.99999, to be sure that this also is still working. Maybe for one for different decimals and one for a number without decimals?

2022-03-02 08:38 UTC, Kirdock commented on bridge/client/app/_pipes/truncate-number.pipe.spec.ts
> +describe('TruncateNumberPipe', () => {
Maybe also add a test for negative numbers and a case to truncate a number to 3 or 1 decimals (a parameter that isn't 2)

2022-03-02 11:04 UTC, Kirdock approved these changes

2022-03-02 11:46 UTC, laneli approved these changes

2022-03-02 13:22 UTC, merged