Add Meg to CONTRIBUTOR.md
keptn/keptn pull request #7199
Opened 2022-03-18 08:25 UTC by StackScribe

2022-03-20 21:16 UTC, oleg-nenashev requested changes
The pull request needs to be fixed. I also recommend following the process in https://github.com/keptn/community/blob/main/COMMUNITY_MEMBERSHIP.md if you want to join the community as an official member

2022-03-20 21:16 UTC, oleg-nenashev commented on helm-service/chart/values.yaml
> +  stageFilter: ""                            # Stage to which this helm service belongs; default is all; comma-separated list to filter for set of stages
Unrelated

2022-03-20 21:16 UTC, oleg-nenashev commented on CONTRIBUTORS.md
> +* [Meg McRoberts](https://github.com/Im5tu)
Wrong GitHub ID

2022-05-17 08:32 UTC, mowies commented
This PR needs a rebase...

2022-08-10 03:46 UTC, closed without merging