feat(bridge): Configure Git upstream via SSH/HTTPS
keptn/keptn pull request #7330
Opened 2022-04-01 07:42 UTC by Kirdock

Closes #6323 
Fixes #7186 

### How to test
- Install/Enable the resource-service
- Bridge: Set the environment variable `RESOURCE_SERVICE_ENABLED` to `true`

2022-04-04 09:26 UTC, ermin-muratovic commented
Can we align the styling of file-input, so that certificate/ssh file upload and shipyard file upload look the same here:

![image](https://user-images.githubusercontent.com/6098219/161514991-3f35434a-9f88-44e4-abd5-e78bd795f9e2.png)

2022-04-04 14:17 UTC, laneli commented
I think it would make sense to have a validator like for ssh://, if a url starts with https://

2022-04-06 08:18 UTC, ermin-muratovic commented
- [ ] On project settings page the "Delete project" section seems to be cut off. Can we add more padding at the bottom here?

![image](https://user-images.githubusercontent.com/6098219/161928767-d516ba15-70c2-4d39-bbc8-c54b1014c375.png)

2022-04-06 09:15 UTC, ermin-muratovic requested changes

2022-04-06 14:00 UTC, ermin-muratovic submitted a review, later dismissed
lgtm

2022-04-06 15:29 UTC, laneli requested changes
* Seems like the validation and error handling for drag and drop is not working properly. I selected a .gvdesign and a .png file and it was just pasted to the text field
![image](https://user-images.githubusercontent.com/2674029/161924532-685675ff-cf49-4ef7-99db-89018bb516fb.png)

2022-04-06 15:29 UTC, laneli commented on bridge/client/app/_interfaces/git-upstream.ts
> +  gitUser?: string;
I guess re-defining this property is not necessary as it is already marked as optional in `IGitData`

2022-04-06 15:29 UTC, laneli commented on bridge/client/app/_services/api.service.ts
> +    return this.http.put(url, {
`this.http.put<unknown>(` ?

2022-04-06 15:29 UTC, laneli commented on bridge/client/app/_utils/git-upstream.utils.spec.ts
> +  it('should not be SSH configuration', () => {
`should not be HTTPS configuration` or `should be SSH configuration`

2022-04-06 15:46 UTC, Kirdock commented on bridge/client/app/_components/ktb-certificate-input/ktb-certificate-input.component.ts
> +      this.certificateControl.markAsDirty();
Just had in mind another component is using this one. If it sets the input parameter wrongly, they should be validated and an error should be shown

2022-04-06 16:16 UTC, Kirdock commented on bridge/client/app/_components/ktb-project-settings-git/ktb-project-settings-git.component.spec.ts
> +    const button = fixture.nativeElement.querySelector('button'); //TODO: move to UI test
Oh, there is the todo I left. I was wondering because SonarCloud did not find it.

2022-04-06 16:32 UTC, Kirdock commented on bridge/client/app/_components/ktb-certificate-input/ktb-certificate-input.component.ts
> +  public readonly allowedExtensions = ['.pem'];
I've added `.crt, .cer, .der`. Should we keep the filter or not? For me, it's handy if you have a lot of files in the desired folder that are not related to a certificate else the user just selects "All files" in the file dialog and that's it.

2022-04-06 16:34 UTC, Kirdock commented on bridge/client/app/_components/ktb-proxy-input/ktb-proxy-input.component.ts
> +        this.hostControl.markAsDirty();
Yes, you are right. Not needed. If there is a value, the `require` validation will not be triggered

2022-04-08 07:06 UTC, laneli commented on bridge/client/app/_components/ktb-certificate-input/ktb-certificate-input.component.ts
> +  public readonly allowedExtensions = ['.pem'];
Yes, also fine by me :)

2022-04-08 07:59 UTC, thisthat commented
We just noticed that the `is insecure` checkbox should not be part only of the proxy configuration. It should be available in general. Changes in the resource-service are also required. Therefore, since this PR is already pretty big, I would suggest doing this adaptation in a follow-up and don't wait for the API change.

2022-04-11 08:28 UTC, Kirdock commented on bridge/client/app/_components/ktb-certificate-input/ktb-certificate-input.component.ts
> +      this.certificateControl.markAsDirty();
I removed it because we don't need it at the moment.

2022-04-11 08:28 UTC, Kirdock commented on bridge/client/app/_components/ktb-ssh-key-input/ktb-ssh-key-input.component.ts
> +        this.privateKeyControl.markAsDirty();
I removed it because we don't need it at the moment.

2022-04-13 06:31 UTC, laneli submitted a review, later dismissed

2022-04-13 07:11 UTC, laneli approved these changes

2022-04-13 07:15 UTC, merged