feat(bridge): Remove tag input field for creating a sequence
keptn/keptn pull request #7757
Opened 2022-05-16 13:51 UTC by heinzburgstaller

## This PR
- Removes input tag
- Change validation
- Adapt unit test
- Adapt integration test
- Add form util function and unit test for it

### Related Issues
Resolves #7704 

### How to test
Ensure that the environment variable `KEPTN_INSTALLATION_TYPE` contains `CONTINUOUS_DELIVERY`
Steps:
1. Trigger sequence
2. Choose delivery
3. Image fields is now full size and tag is removed

2022-05-16 13:59 UTC, ermin-muratovic requested changes

2022-05-16 13:59 UTC, ermin-muratovic commented on bridge/cypress/integration/trigger-sequence.spec.ts
> -      .typeDeliveryTag('v0.1.2')
This method could also be removed from `TriggerSequenceSubPage.ts`

2022-05-16 14:03 UTC, thisthat commented
Thank you @heinzburgstaller for your contribution 🙌 Could you please attach a screenshot how the UI looks like to the PR description?

2022-05-17 06:40 UTC, heinzburgstaller commented
> Thank you @heinzburgstaller for your contribution raised_hands Could you please attach a screenshot how the UI looks like to the PR description?

Done

2022-05-18 15:39 UTC, ermin-muratovic submitted a review, later dismissed
lgtm. 
can't reproduce the failed UI test. maybe a flaky test, but not a concern of this issue.

2022-05-24 07:28 UTC, ermin-muratovic approved these changes
lgtm

2022-05-24 07:28 UTC, merged