fix(cli): Remove unnecessary `--sequence` flag from `keptn trigger sequence`
keptn/keptn pull request #7902
Opened 2022-05-30 10:02 UTC by odubajDT

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- removed --sequence flag from command

### Related Issues

Fixes #7884

2022-05-30 10:23 UTC, thisthat requested changes
~There could be multiple delivery sequences in a shipyard file, hence the flag should not be removed instead, it should be made optional.~

2022-05-30 11:56 UTC, RealAnna requested changes
please fix integration tests

2022-05-30 11:58 UTC, RealAnna approved these changes

2022-05-30 12:01 UTC, merged

2022-06-03 05:24 UTC, odubajDT commented
Hi @agardnerIT, no it was not, we do consider this problem as low priority, so no backports were made. Do you have a specific reason why it should be backported to 0.15.x?

Thanks.