fix(bridge): Remove previous filter from URL
keptn/keptn pull request #7998
Opened 2022-06-03 11:58 UTC by heinzburgstaller

## This PR
- Fix component
- Add UI test

Fixes #7978

2022-06-03 12:14 UTC, Kirdock requested changes
We have two other places where the adjustment is needed.
1. https://github.com/keptn/keptn/blob/d82e52d220ddd39ea50764a6691c35084cde5430/bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.ts#L64
2. https://github.com/keptn/keptn/blob/d82e52d220ddd39ea50764a6691c35084cde5430/bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts#L427

2022-06-03 12:14 UTC, Kirdock commented on bridge/cypress/integration/sequences.spec.ts
> +    it.only('should not add the filter to the URL after it was cleared and the page was reloaded', () => {
Please remove the `only` here

2022-06-07 06:36 UTC, heinzburgstaller commented on bridge/cypress/integration/sequences.spec.ts
> +    it.only('should not add the filter to the URL after it was cleared and the page was reloaded', () => {
Done

2022-06-07 06:37 UTC, heinzburgstaller commented
> We have two other places where the adjustment is needed.
> 
>     1. https://github.com/keptn/keptn/blob/d82e52d220ddd39ea50764a6691c35084cde5430/bridge/client/app/_components/ktb-sequence-tasks-list/ktb-sequence-tasks-list.component.ts#L60-L69
> 
>     2. https://github.com/keptn/keptn/blob/d82e52d220ddd39ea50764a6691c35084cde5430/bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts#L423-L433

Done

2022-06-07 13:59 UTC, merged