Prod
keptn/keptn pull request #8179
Opened 2022-06-24 13:44 UTC by Brijesh-09

## This PR
Cleanup of obsolete feature in Bridge https://github.com/keptn/keptn/issues/7378

### Related Issues
Removed the button Load more information about integrations and below label

Fixes #7378

2022-06-27 11:20 UTC, Kirdock requested changes
- [x] Could you update your PR name to something like `feat(bridge): Cleanup of obsolete feature in Bridge`. Here you can see the pattern: https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#commit-types-and-scopes
- [ ] The yarn.lock isn't updated. Could you remove `highlight.js` via `yarn remove highlight.js`?
- [ ] Seems like the dependencies `dompurify` and `marked` can also be removed.

2022-06-27 11:20 UTC, Kirdock commented on bridge/server/app.ts
> -let integrationsPageLink: string | undefined = process.env.INTEGRATIONS_PAGE_LINK;
With this being removed, could you also remove the other usages? Else there will be a compile error

2022-06-27 12:26 UTC, Kirdock commented on bridge/server/app.ts
> -let integrationsPageLink: string | undefined = process.env.INTEGRATIONS_PAGE_LINK;
> where I can find the other usages

It's right below:
https://github.com/keptn/keptn/blob/60be3bfb7e9cd1d8934c95a02074d7be71585319/bridge/server/app.ts#L82-L85

2022-06-27 12:39 UTC, Kirdock commented
With `highlight.js` being removed, this line must also be deleted:
https://github.com/keptn/keptn/blob/60be3bfb7e9cd1d8934c95a02074d7be71585319/bridge/angular.json#L45

2022-06-27 13:13 UTC, ermin-muratovic commented
@Brijesh-09 thank you for squashing your changes. I know that there were many conflicts, because we changed a lot of code in the past days by introducing modules to Keptn's Bridge.

Please make sure to remove this two occurances of `KtbMarkdownComponent` and fix the suggestions from @Kirdock and I hope we will be able to merge your PR soon:

https://github.com/keptn/keptn/blob/60be3bfb7e9cd1d8934c95a02074d7be71585319/bridge/client/app/app.module.ts#L68

https://github.com/keptn/keptn/blob/60be3bfb7e9cd1d8934c95a02074d7be71585319/bridge/client/app/app.module.ts#L252

2022-06-27 13:19 UTC, Kirdock requested changes
This is now also deprecated and can be removed:
https://github.com/keptn/keptn/blob/60be3bfb7e9cd1d8934c95a02074d7be71585319/installer/manifests/keptn/templates/core.yaml#L112-L113

2022-06-30 13:02 UTC, Kirdock requested changes
- [ ] You committed some merge conflicts.
- [ ] You can also remove the `marked` dependency, as it is not used anymore now.
- [ ] The `yarn.lock` also needs to be adjusted.
If `yarn` is unclear: `yarn` is a package manager like `npm` and you can install it via `npm i yarn -g`. If you remove a dependency inside the package.json, always remove it via the command `yarn remove myDependency`. Yarn will maintain the `yarn.lock` file then and if you just simply remove it manually in the `package.json`, the lock file isn't adjusted. The `yarn.lock` file must not be touched on your own, yarn will do all the work here.

2022-07-08 07:45 UTC, Kirdock commented
Closed in favor of #8344

2022-07-08 07:45 UTC, closed without merging