feat(bridge): Modularize dashboard view and introduce lazy loading
keptn/keptn pull request #8315
Opened 2022-07-06 08:37 UTC by TannerGilbert

## This PR

- Moves dashboard inside `_views` folder
- Modularizes dashboard views
- Adds lazy loading

### Related Issues

Part of #8034

Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

2022-07-08 08:35 UTC, Kirdock requested changes

2022-07-08 08:35 UTC, Kirdock commented on bridge/client/app/_views/ktb-dashboard-legacy-view/ktb-dashboard-legacy-view.component.scss
> +@import 'node_modules/@dynatrace/barista-components/core/src/style/variables';
Could you change it to be relative again?
```suggestion
@import '../../../variables';
@import '~@dynatrace/barista-components/core/src/style/variables';
```

2022-07-08 08:35 UTC, Kirdock commented on bridge/client/app/_views/ktb-dashboard-legacy-view/ktb-dashboard-legacy-view.module.ts
> +    KtbSequenceStateListModule,
This module is also only used for the dashboard. Therefore it can be removed and the containing imports can be added here

2022-07-12 11:01 UTC, ermin-muratovic requested changes

2022-07-12 11:01 UTC, ermin-muratovic commented on bridge/client/app/_views/ktb-dashboard-legacy-view/ktb-dashboard-legacy-view.component.ts
> +export class KtbDashboardLegacyViewComponent {
Could be named just `KtbDashboardViewComponent` without the `Legacy`, same goes for the `Module`.

2022-07-12 11:02 UTC, Kirdock requested changes

2022-07-12 11:02 UTC, Kirdock commented on bridge/client/app/_views/ktb-dashboard-legacy-view/ktb-dashboard-legacy-view.module.ts
> +    RouterModule,
The `RouterModule` here is actually redundant because the `KtbDashboardLegacyViewRoutingModule` already imports/exports it

2022-07-12 11:31 UTC, ermin-muratovic submitted a review, later dismissed
lgtm

2022-07-12 11:59 UTC, Kirdock requested changes

2022-07-12 11:59 UTC, Kirdock commented on bridge/client/app/_views/ktb-dashboard-view/ktb-dashboard-view.component.spec.ts
> +describe('DashboardLegacyView', () => {
Could you also rename it to `DashboardView`, `KtbDashboardView`or `KtbDashboardViewComponent`?

2022-07-12 12:57 UTC, Kirdock approved these changes

2022-07-12 13:03 UTC, merged