feat(bridge): integrate storybook
keptn/keptn pull request #8496
Opened 2022-07-22 07:55 UTC by renepanzar

## This PR

Adds Storybook.js to the bridge so we can develop components independently from their context. It also acts as documentation for the components and best practices.

### Notes

![image](https://user-images.githubusercontent.com/34232562/180391428-84766fe8-942d-419a-ba91-0c800d4c55ca.png)

### Follow-up Tasks

Best practices will be added later on.

### How to test

1. `yarn storybook` will start the Storybook development server and open the endpoint in a browser
2. Click through the stories

2022-07-27 14:37 UTC, Kirdock requested changes
There is still a bunch of errors in the console.
e.g.:
![image](https://user-images.githubusercontent.com/11599148/181272013-b57374e8-4b77-489b-9729-ac4d0271742d.png)
![image](https://user-images.githubusercontent.com/11599148/181273115-e55441e2-0706-4aee-8eff-9c0dc10aa667.png)

and the certificate-input for example also throws a lot of errors
![image](https://user-images.githubusercontent.com/11599148/181273398-b58c5559-3daf-42e9-b292-b8a191cbfbf2.png)


At the moment the project is not set in the header anymore if you refresh the page
![image](https://user-images.githubusercontent.com/11599148/181273834-a3c4d7c0-a957-4507-9caf-9da82659016f.png)

2022-07-27 14:37 UTC, Kirdock commented on bridge/client/app/_components/ktb-date-input/ktb-date-input.module.ts
> +    RouterModule,
Why do we need the RouterModule here?

2022-07-27 14:37 UTC, Kirdock commented on bridge/client/app/_components/ktb-copy-to-clipboard/ktb-copy-to-clipboard.module.ts
> +    HttpClientModule,
Could you move that to the imports of the required story instead?

2022-07-27 14:37 UTC, Kirdock commented on bridge/client/app/_components/ktb-app-header/ktb-app-header.module.ts
> +    HttpClientModule,
Could you move that to the imports of the required story instead?

2022-07-27 14:37 UTC, Kirdock commented on bridge/stories/components/Heatmap.stories.ts
> +      imports: [KtbHeatmapModule],
`HttpClientModule` is missing here

2022-07-27 14:37 UTC, Kirdock commented on bridge/stories/components/Components.stories.mdx
> +</div>
Could you remove this test data?

2022-07-28 06:52 UTC, ermin-muratovic requested changes

2022-07-28 06:52 UTC, ermin-muratovic commented on bridge/.gitignore
> +/documentation.json
It looks like `/documentation.json` belongs to the group `# certificates`.
Could you add a new comment `# storybook` and move this below that.

2022-07-28 12:05 UTC, ermin-muratovic approved these changes
lgtm

2022-07-29 06:31 UTC, Kirdock requested changes
Some components still throw some errors.
- [x] Certificate input: When you manually change the input:
![image](https://user-images.githubusercontent.com/11599148/181696383-cbc40a0b-37fe-422f-93f8-276c46dcc9de.png)
- [x] Expandable tile: The tile immediately closes for the "Expanded" story.
- [x] App Header: There is an error thrown if you select a project

- [ ] I guess the global styles.scss is missing here. That would explain some incorrect styles, like for the copy-clipboard icon

2022-07-29 06:52 UTC, renepanzar commented
Thanks, @Kirdock, for your comments.

I've fixed the certificate input issues.

The expandable tile does have an issue, though, it doesn't want to stay opened. This needs to be fixed inside the component.

The app-header does not produce an error any longer with missing route.

The icon in the clipboard component needs to be re-styled, it's an issue with the component itself. The global styles are loaded, or else it would look like the following (app-header):

![image](https://user-images.githubusercontent.com/34232562/181699958-7e83ef6d-4d2b-4b69-9fab-706a4e387af4.png)

2022-07-29 07:06 UTC, renepanzar commented
Out of curiosity I tried to fix the expandable tile, which now works.

2022-07-29 07:46 UTC, Kirdock requested changes

2022-07-29 07:46 UTC, Kirdock commented on bridge/.storybook/tsconfig.json
> +  "include": ["../src/**/*", "../projects/**/*"],
Those paths do not exist.

2022-07-29 07:48 UTC, Kirdock commented on bridge/.storybook/tsconfig.json
> +  "include": ["../src/**/*", "../projects/**/*"],
Same for `tsconfig.doc.json`

2022-08-01 06:05 UTC, Kirdock approved these changes

2022-08-01 06:56 UTC, merged