feat(bridge): link to current running sequence
keptn/keptn pull request #8567
Opened 2022-08-03 11:01 UTC by TannerGilbert

## This PR

- adds link to current running sequence if the selected sequence is blocked

### Related Issues

Resolves #7635

### Notes

![link-to-blocking-sequence](https://user-images.githubusercontent.com/36239763/182592249-e79b69e1-6cc4-40b6-be32-de5d8c37db58.png)

![link-to-blocking-sequence-II](https://user-images.githubusercontent.com/36239763/182592274-e6d6efcf-96e8-4c66-88df-2c5afb5f7041.png)

[link-to-blocking-sequence.webm](https://user-images.githubusercontent.com/36239763/182592610-6038f406-7bc5-401c-8a1f-6e3468bcbb7c.webm)

2022-08-09 06:10 UTC, Kirdock requested changes

2022-08-09 06:10 UTC, Kirdock commented on bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
> +  public navigateToBlockingSequence(currentSequence: SequenceState, state?: ISequenceViewState): void {
Could you add some unit tests for this function?

2022-08-09 12:07 UTC, TannerGilbert commented on bridge/cypress/integration/sequences.spec.ts
> +  it.only('should navigate to blocking sequence', () => {
Tested this behavior using unit tests.

2022-08-09 12:08 UTC, TannerGilbert commented on bridge/cypress/support/pageobjects/SequencesPage.ts
>    private readonly sequenceWaitingMessage = ' Sequence is waiting for previous sequences to finish. ';
This message is still used inside the `ktb-root-events-list.component`

2022-08-09 14:53 UTC, Kirdock requested changes
I guess we need a fallback for the stage
In this case
![image](https://user-images.githubusercontent.com/11599148/183681002-a8ff173e-e468-4a30-9be1-4b0f5afc9589.png)
we don't have any stages.

We should discuss how we should handle that.

2022-08-09 14:53 UTC, Kirdock commented on bridge/shared/interfaces/sequence-execution-result.ts
> +  state: 'triggered' | 'waiting' | 'suspended' | 'paused' | 'finished' | 'cancelled' | 'timedOut';
Could you also add 'started' here? And maybe move it into a separate type variable and use that for the status property of the sequence-execution API call in the apiService.

2022-08-10 12:04 UTC, TannerGilbert commented
I added code to sort the stages when calling `${this._baseUrl}/project/${projectName}/sequences/filter` to allow us to use the `metadata` object in the `ktb-sequence-view.component.ts` to get the available sequences. The sorting however doesn't help us navigate to the correct next stage if there are multiple parent stages. For this, we would need to update the [getSequencesFilter method](https://github.com/keptn/keptn/blob/29c9e7d6d250cde8247558df1303a72c900d4540/bridge/server/services/data-service.ts#L1242) to also return the parentStages of each individual stage.

2022-08-11 06:08 UTC, Kirdock submitted a review, later dismissed

2022-08-11 06:08 UTC, Kirdock commented on bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts
> +          this.navigationToRunningSequenceLoading = false;
This is not necessary because it is already set in `finalize`

2022-08-11 06:08 UTC, Kirdock commented on bridge/cypress/support/pageobjects/SequencesPage.ts
> +  public assertDtAlert(status: boolean): this {
Could you make it more clear in the function name what it does?
```suggestion
  public assertDtAlertExists(status: boolean): this {
```

2022-08-16 08:15 UTC, heinzburgstaller approved these changes
Next time: Changing a naming will be in a separate PR please ;)

2022-08-16 08:25 UTC, merged