fix(bridge): Stop navigation overwrite on trace load
keptn/keptn pull request #8617
Opened 2022-08-10 13:03 UTC by TannerGilbert

## This PR

- Removes overwriting of stage selection by `setTraces$` timer

### Related Issues

Fixes #8614. Fixes #8648

### Notes

The `setTraces$` timer inside the `ktb-sequence-view.component.ts` wasn't updated when selecting a stage from the `ktb-sequence-timeline`. It, therefore, navigated back to the stage it was last instantiated with.

2022-08-10 14:22 UTC, heinzburgstaller reviewed
The name change makes the PR too big

2022-08-11 06:00 UTC, Kirdock commented on bridge/shared/interfaces/sequence.ts
> +export interface ISequenceState {
I guess he branched away from #8567. Let's merge the other PR first, then this one will probably much smaller

2022-08-16 08:53 UTC, heinzburgstaller approved these changes

2022-08-16 08:54 UTC, heinzburgstaller requested changes
Want to wait for UI tests

2022-08-16 10:43 UTC, heinzburgstaller approved these changes

2022-08-16 10:45 UTC, merged