added info about auto-signoff
keptn/keptn pull request #8915
Opened 2022-09-29 18:53 UTC by nitinmewar

Signed-off-by: nitin mewar <nitinmewar28@gmail.com>

### Related Issues

Fixes #8914 

### Notes
added info about auto-signoff in the CONTRIBUTING.md

2022-09-30 20:36 UTC, iamrajiv requested changes
@nitinmewar Please format the code something like this

# Contributing

First off, thank you for considering contributing to Keptn! It's people like you who make Keptn great.

- **Create an issue**: If you have noticed a bug, want to contribute features, or simply ask a question that for whatever reason you do not want to ask in the [Keptn Slack workspace](https://slack.keptn.sh), please [search the issue tracker](https://github.com/keptn/keptn/issues?q=something) to see if someone else in the community has already created a ticket. If not, go ahead and [create an issue](https://github.com/keptn/keptn/issues/new).

- **Start contributing**: We also have a list of [good first issues](https://github.com/keptn/keptn/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). If you want to work on it, just post a comment on the issue.

- **Add yourself**: Add yourself to the [list of contributors](CONTRIBUTORS.md) along with your first pull request.

This document lays out how to get you started in contributing to Keptn, so please read on.

## Documentation

The Keptn repository is a monorepo with multiple sub-folders that contain microservices, the installer, Keptn Bridge,
and the `keptn` CLI.
As a starting point, please read the README files in the respective sub-folder. Also, take a look at the docs within the [docs/](docs/) folder in this repository.

We are aware that not every microservice has comprehensive documentation, so if you have any questions feel free to ask us in the [Keptn Slack workspace](https://slack.keptn.sh).

## Development Process

Within the Keptn project, several features of GitHub are used to control the development process. For instance, you can
find the [Roadmap](https://github.com/orgs/keptn/projects/1) as a [GitHub Project Board](https://github.com/orgs/keptn/projects).

In addition, we use GitHub Issues as the primary method for tracking concrete implementation tasks, bugs, etc...

### Keptn Enhancement Proposals and GitHub Issues

Proposing new functionality for Keptn is a transparent process done via a so-called [Keptn Enhancement Proposal](https://github.com/keptn/enhancement-proposals).
This is required when the proposed functionality is intended to introduce new behaviour, change desired behaviour, or otherwise modify the requirements of Keptn.

If all you want to propose is a simple addition to a Keptn-service, Bridge or the CLI, a typo, or just a bugfix, please open [a new issue on GitHub](https://github.com/keptn/keptn/issues/new/choose) and try to label it accordingly.

If you are unsure, just open a [new issue](https://github.com/keptn/keptn/issues/new/choose) and we will label it for you or direct you to an enhancement proposal if necessary.

### Working items

We use GitHub Issues as the primary method for tracking concrete implementation tasks (e.g., an enhancement proposal can
lead to multiple issues). In addition, we use a [GitHub Project Board](https://github.com/keptn/keptn/projects) to
plan and assign the working items for the next upcoming days. This board is discussed and presented publicly in our
[weekly community meeting](https://github.com/keptn/community#%EF%B8%8F-community-meetings).

### Bug first policy

We derived the following labels based on the Blog Post [Zero-Bug Software Development](https://www.xolv.io/blog/zero-bug-software-development/)
to classify the importance of work tasks with GitHub issues:

- `type:critical` - This is a **defect** that causes us and/or our end-users/stakeholders to lose a significant amount
  of time, money and/or value.
- `type:bug` - Something is not working as intended or documented and therefore needs to be fixed (either by writing
  code or by adapting the documentation).
- `type:feature` - This indicates that the issue contains a completely new feature that provides value for our
  end-users/stakeholders, most likely in combination with a `kep:XYZ` label
- `type:improvement` - This label should be used for indicating that something is just an improvement of an existing
  feature.
- `type:chore` - Chores are issues that provide value to the (developer) team, e.g., cleanups, automation, etc...
  (things that keep our team productive and efficient)

**Please note**: The Keptn maintainers reserve the right to change the labels to the best of their knowledge.

Based on the labels above, we try to adhere to the following bug first policy:

- Issues labeled with `type:critical` need to be addressed right away (either with a comment, a workaround, or a fix).
  The rule is: stop what you are doing and fix it.
- Issues labeled with `type:bug` need to have a response within 3 business days and a workaround or fix needs to be
  provided within 10 business days.
- Issues labeled with `type:feature`, `type:improvement` or `type:chore` will be worked on as per the backlog priority
  order.

**Please note**: This is a policy, not an enforced rule. The Keptn maintainers will do their best to follow this policy.

### Other labels

There are many other labels that either indicate that a feature belongs to a certain part of Keptn (e.g., `bridge`,
`cli`, `core`, ...) or to an enhancement proposal (e.g., `kep:06`). In addition, we use the labels `good first issue`
to indicate that this issue is good to get started with contributing to Keptn.

### Fork Repositories and work in a branch

For contributions to Keptn, please fork the Keptn repository and work in a branch. More information about forking is written down in the [docs/fork](docs/developer/fork.md).

We are loosely following the [Git Flow branching model](https://nvie.com/posts/a-successful-git-branching-model/) however, we try to avoid the extra step of the `develop` branch and instead work directly on the `master` branch.

- If you work on an improvement, [fork the repository](docs/developer/fork.md), branch away from the `master` branch, and use the following schema for naming your branches:

```

<ticket-type>/<github-issue-number>/<descriptive-name-with-dashes>

Examples:
feat/1234/my-new-feature
fix/2235/important-bugfix

```

All possible ticket/commit/PR types and scopes can be found [here](#commit-types-and-scopes).

- If you work on a hotfix and a maintenance branch for the related release(s) doesn't exist yet, please create a maintenance branch with the following naming scheme:
  If the release was e.g. `v0.8.6`, the maintenance branch should be named `0.8.x` and it should have the faulty release as its base instead of master.
  Then, you can create a bugfix branch from the **master** branch and work on the hotfix. When you are done, please create a PR against the master branch.
  The merged commit should then cherry-pick to the maintenance branch and then the hotfix release can be created.

**Note:** The `###` part of the branch has to reference the GitHub issue number, e.g., if you work on the feature described in issue `#1234`, the branch name would be: `feature/1234/my-feature`.

### Follow Coding Style

When contributing code to Keptn, we politely ask you to follow the coding style suggested by the [Golang community](https://github.com/golang/go/wiki/CodeReviewComments).
We are running automated code style checks for pull requests using the following tools:

- [reviewdog](.reviewdog.yml) - automatic code review
  - `golint ./...`
  - `gofmt -l -s .`
- [codecov.io](codecov.yml) - tracks code coverage based on unit tests

### Following Coding Style for Bridge

For Bridge development setup and coding guidelines, please consult the Bridge [README.md](https://github.com/keptn/keptn/blob/master/bridge/README.md).

### Boy Scout Rule

> Always leave the code better than you found it!

While we would all like to make the world better all the time, please apply common sense to this rule, for instance:

- When you're fixing a bug, don't refactor code around the bug (in fact, this could be counter-productive for backports/cherry-picks).
- Do not change or extend the scope of your issue (e.g., stay within the mic [...]

2022-10-01 10:27 UTC, nitinmewar commented
@iamrajiv I couldn't find where is the problem. first I thought it is because of PR name which I changes but it's still same.

2022-10-03 06:20 UTC, mowies commented
@nitinmewar I fixed your PR title :)

2022-10-03 06:21 UTC, mowies commented
@iamrajiv Why not use the suggestion functionality in the PR review? Maybe then it's easier to see what you changed :D

2022-10-03 16:08 UTC, nitinmewar commented
@mowies thanks ✌️

2022-10-03 18:02 UTC, oleg-nenashev approved these changes
+1

2022-10-04 06:13 UTC, mowies requested changes
Thank for the contribution, I left a few comments for you

2022-10-04 06:13 UTC, mowies commented on CONTRIBUTING.md
> +Make sure you sign-off your commits. To do this automatically check [this](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#auto-signoff-commit-messages). Finally, go to GitHub and create a
```suggestion
Make sure you sign off your commits. To do this automatically check [this](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#auto-signoff-commit-messages). Finally, go to GitHub and create a Pull Request. There should be a PR template already prepared for you.
```

2022-10-04 06:13 UTC, mowies commented on CONTRIBUTING.md
> +```
```suggestion
You can do 
```bash
git commit --amend --signoff
```

or something like
```bash
git rebase HEAD~2 --signoff
```
```

2022-10-04 06:13 UTC, mowies commented on CONTRIBUTING.md
> +to signoff commits, but it is inconvenient. You can automate this process.
```suggestion
to sign off commits, but it is inconvenient. You can automate this process.
```

2022-10-04 06:13 UTC, mowies commented on CONTRIBUTING.md
> +To automatically signoff commits  :
```suggestion
To automatically sign off commits:
```

2022-10-04 14:45 UTC, nitinmewar commented
I did something extremely wrong I think?

2022-10-18 12:13 UTC, mowies commented
@nitinmewar you could re-do your changes on a new branch and create a new PR...

2022-11-03 10:25 UTC, closed without merging