feat(bridge): Show full date on hover on sequence view
keptn/keptn pull request #8997
Opened 2022-10-12 12:34 UTC by TannerGilbert

## This PR

- Show full date on hover on sequence view

### Related Issues

Resolves #7719

### Notes

![show-full-date-on-hover](https://user-images.githubusercontent.com/36239763/195343779-ff1e91cf-2e09-4950-9e24-d1bbc200841b.png)

Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

2022-10-12 14:52 UTC, thisthat requested changes

2022-10-12 14:52 UTC, thisthat commented on bridge/client/app/_views/ktb-sequence-view/ktb-sequence-timeline/ktb-sequence-timeline.component.html
> +            [textContent]="time | date: 'HH:mm'"
please use `YYYY-MM-dd HH:mm:ss` as format

2022-10-13 07:27 UTC, Kirdock requested changes

2022-10-13 07:27 UTC, Kirdock commented on bridge/client/app/_views/ktb-sequence-view/ktb-sequence-tasks-list/ktb-task-item.component.html
> +              <span>{{ task.time | amDateFormat: dateUtil.getDateTimeFormat() }}</span>
This one should also be in seconds, to be aligned with the other overlays I guess.

2022-10-13 07:58 UTC, Kirdock approved these changes

2022-10-13 08:53 UTC, thisthat commented on bridge/cypress/support/pageobjects/SequencesPage.ts
> +      overlay.children().should('have.length.greaterThan', 0);
this check only looks for a string with lenght > 0, right? 
I would suggest, if possible, to verify for the regex `[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}`

2022-10-13 09:12 UTC, thisthat approved these changes

2022-10-13 09:19 UTC, merged