chore: Move to full release
keptn/keptn pull request #9044
Opened 2022-10-18 07:31 UTC by mowies

### This PR
- removes release-please settings so that the next version will be 1.0.0

2022-10-18 07:37 UTC, philipp-hinteregger requested changes

2022-10-18 07:37 UTC, philipp-hinteregger commented on release-please-config.json
>          "prerelease": false,
```suggestion
```

2022-10-18 07:37 UTC, philipp-hinteregger commented on release-please-config.json
>          "prerelease": false,
I think we don't need this anymore too

2022-10-18 07:41 UTC, philipp-hinteregger approved these changes
LGTM

2022-10-18 08:03 UTC, thisthat requested changes
Looking forward to merge this PR :D 
I am asking for changes just to block it until we are fully ready to officialize the LTS release

2022-12-07 17:24 UTC, thisthat approved these changes
All pieces for Keptn v1.0.0 have been merged 🎉

2022-12-12 07:10 UTC, merged